"""
PDF Generator for TourCrafts
Generates downloadable itinerary PDFs for packages.
Requires: pip install fpdf2
"""

# Placeholder for PDF generation service
# In production, this would use fpdf2 or reportlab to generate actual PDFs


def generate_itinerary_pdf(package_data: dict, tier: str = "deluxe") -> bytes:
    """
    Generate a PDF itinerary for a given package.
    
    Args:
        package_data: Dictionary containing package details
        tier: Selected tier (budget/deluxe/premium)
    
    Returns:
        PDF content as bytes
    """
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Header
        pdf.set_font("Helvetica", "B", 24)
        pdf.cell(0, 15, "TourCrafts", align="C", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 8, "Handcrafted Travel Experiences", align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(10)

        # Package Title
        pdf.set_font("Helvetica", "B", 18)
        title = package_data.get("title", "Tour Package")
        pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 8, f"Destination: {package_data.get('destination', '')}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 8, f"Duration: {package_data.get('duration', '')}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 8, f"Selected Tier: {tier.capitalize()}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(10)

        # Itinerary
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "Day-wise Itinerary", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        itinerary = package_data.get("itinerary", [])
        for day in itinerary:
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, f"Day {day.get('day', '')}: {day.get('title', '')}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, day.get("description", ""))
            pdf.ln(3)

        # Footer
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 8, "Generated by TourCrafts | www.tourcrafts.com | +91 98765 43210", align="C")

        return pdf.output()

    except ImportError:
        return b"PDF generation requires fpdf2. Install with: pip install fpdf2"


def generate_proposal_pdf(package_data: dict, client_name: str, tier: str = "deluxe") -> bytes:
    """
    Generate a client proposal PDF.
    This is an extended version with pricing and terms.
    """
    # Placeholder - extend generate_itinerary_pdf with pricing tables and T&C
    return generate_itinerary_pdf(package_data, tier)
